# Generated by Django 5.0.2 on 2024-02-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_post_created_at_remove_post_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='creator',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
