# Generated by Django 5.0.2 on 2024-02-07 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creator',
            new_name='author',
        ),
    ]
