# Generated by Django 5.0.2 on 2024-02-08 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='Content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
