# Generated by Django 5.0.2 on 2024-02-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Like_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='isLiked',
            field=models.BooleanField(default='1'),
            preserve_default=False,
        ),
    ]
